#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 16 21:19:53 2020

@author: sandesh
"""
import math

def HammingDist(Pattern, text):
    count = 0
    for i in range(0, len(Pattern)):
        if Pattern[i] != text[i]:
            count = count +1
    return count

def DistanceBetweenPatternandString(Pattern, Dna):
    k = len(Pattern)
    distance = 0
    for text in Dna:
        HammingDistance = math.inf
        for i in range(0, len(text)-k+1):
            pat = text[i:i+k]
            HD = HammingDist(Pattern, pat)
            if HammingDistance > HD:
                HammingDistance = HD
        
        distance = distance + HammingDistance
    return distance

Dna = ["ACTACGA", "GTACGATC", "ATGACAT"]
Pattern = "ACTA"
print(DistanceBetweenPatternandString(Pattern, Dna))