#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 14 13:26:42 2020

@author: sandesh
"""

#REVERSE COMPLEMENT

def reversecomplement(DNA):
    DNAlist = list(DNA)
    print(DNAlist)
    
    for i in range(0,len(DNAlist),1):
        if DNAlist[i] == "A":
            DNAlist[i] = "T"
        elif DNAlist[i] == "G":
            DNAlist[i] = "C"
        elif DNAlist[i] == "C":
            DNAlist[i] = "G"
        elif DNAlist[i] == "T":
            DNAlist[i] = "A"
        
    DNAlist.reverse()
    revcom = ''.join(DNAlist[0: len(DNAlist)])
    return revcom
        
DNA = input("Enter the DNA String in Capital")
print(reversecomplement(DNA))