#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 14 13:52:26 2020

@author: sandesh
"""



def startpos(string, pattern ):
    Positions = set()
    a = len(string) - len(pattern) +1
    stringl = list(string)
    patternl = list(pattern)
    
    for i in range(0,a,1):
        m = 0
        for j in range(0, len(patternl),1):
            if patternl[j] == stringl[i]:
                m = m+1
                i = i +1
        if m == len(patternl):
            k = i - len(patternl) +1
            Positions.add(k)
    
    return(Positions)

string = input("Please enter the string")
pattern = input("Please enter the pattern:")
print(startpos(string, pattern))