#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 18:55:20 2020

@author: sandesh
"""
def PatternFind(string, pattern, window):
    a = len(string) - window +1
    b = window- len(pattern) +1
    Count = [None]*a
   
    for i in range(0,a,1):   
        t =i
        count = 0
        for s in range(0,b,1):
            m = 0
            k = t
            for j in range(0, len(pattern), 1):
                if pattern[j] == string[k]:
                    m = m+1
                    k = k+1
            t = t+1
            if m   == len(pattern):
                count = count +1
            Count[i] = count
    return(max(Count))

def FrequentWords(string, kmer, window):
    a = len(string) - kmer +1
    Frequentword = set()
    PositionWin = set()
    Counts = [None] * a
    for i in range(0, a, 1):
        Pattern = string[i:i+kmer]
        Counts[i] = PatternFind(string, Pattern, window)
        if Counts[i] >1:
            adds = ''.join(Pattern)
            Frequentword.add(adds)
    return Frequentword
   
#Taking DNA String as input and changing it into list. Also, taking kmer as input.
DNA = input("Enter your DNA String in Capital: \n")
string = list(DNA)
kmer = int(input("Enter the k-mer of frequentwords:"))
window = int(input("Enter the window:"))
print(FrequentWords(string, kmer, window))           
        
            

#Function to return how many times a pattern is repeated in a string
