#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 20 19:25:50 2020

@author: sandesh
"""

#Hamming's Distance with two strings of equal length

stringa = input("Enter string1 in all capital please")
string1 = list(stringa)
stringb = input("Enter string2 in all capital please")
string2 = list(stringb)
count = 0

for i in range(0, len(string1), 1):
    if string1[i] != string2[i]:
        count = count+1

print("The Hamming's Distance is", count,".")    