#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug  9 09:02:09 2020

@author: sandesh
"""

def NumbertoPattern(index, k):
    if k == 1:
        return NumbertoSymbol(index)
    prefix_index = index // 4
    remainder = index % 4
    symbol = NumbertoSymbol(remainder)
    PrefixPattern = NumbertoPattern(prefix_index, k-1)
    pat = PrefixPattern + symbol
    return pat

def NumbertoSymbol(r):
    if r == 0:
        return 'A'
    elif r == 1:
        return 'C'
    elif r == 2:
        return'G'
    elif r == 3:
        return 'T'


print(NumbertoPattern(722,6))