#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 16 23:25:23 2020

@author: sandesh
"""

def String_GenomePath(Patterns):
    k = len(Patterns[0])
    
    for i in range(1, len(Patterns)):
        
        Patterns[i] = Patterns[i-1] + Patterns[i][k-1] #add the last symbol of each element of pattern to the element preceding it and iterate till the last element
    
    return(Patterns[i])
        

Patterns = ['TAT', 'ATG', 'TGG', 'GGG', 'GGG', 'GGT', 'GTG', 'TGC']
print(String_GenomePath(Patterns))